services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: dissertatsiya
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: alisher
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"   # Host'dan 5433 orqali kirish mumkin (mahalliy Postgres bilan to'qnashmasin uchun)
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build: .
    env_file: .env.docker
    volumes:
      - media_data:/app/media
      - protected_media_data:/app/protected_media
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  celery_worker:
    build: .
    command: celery -A config worker -l info
    env_file: .env.docker
    volumes:
      - media_data:/app/media
      - protected_media_data:/app/protected_media
    depends_on:
      - backend

  celery_beat:
    build: .
    command: celery -A config beat -l info
    env_file: .env.docker
    depends_on:
      - backend

  frontend:
    build: ../frontend
    volumes:
      - ../frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://127.0.0.1:8000/api
    depends_on:
      - backend

volumes:
  postgres_data:
  media_data:
  protected_media_data: