"""
Bemorning kasallik tarixini PDF hujjat sifatida generatsiya qilish.
Uch tilni qo'llab-quvvatlaydi: uz (o'zbek), ru (rus), en (ingliz).
"""

import os
from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image,
)

TRANSLATIONS = {
    "uz": {
        "title": "Bemor kasallik tarixi",
        "meta": "MedKarta tizimi orqali generatsiya qilingan hujjat. Ushbu hujjat maxfiy ma'lumotlarni o'z ichiga oladi.",
        "full_name": "F.I.Sh.",
        "birth_date": "Tug'ilgan sana",
        "gender": "Jinsi",
        "blood_type": "Qon guruhi",
        "allergies": "Allergiyalar",
        "records_title": "Tibbiy yozuvlar ({count} ta)",
        "no_records": "Hozircha tibbiy yozuvlar mavjud emas.",
        "type": "Turi",
        "doctor": "Shifokor",
        "diagnosis": "Tashxis",
        "treatment": "Davolash",
        "notes": "Izoh",
        "not_set": "—",
        "gender_M": "Erkak", "gender_F": "Ayol", "gender_O": "Boshqa",
        "record_types": {
            "visit": "Tashrif", "diagnosis": "Tashxis", "prescription": "Retsept",
            "lab_result": "Laboratoriya natijasi", "procedure": "Muolaja",
        },
    },
    "ru": {
        "title": "История болезни пациента",
        "meta": "Документ создан системой MedKarta. Данный документ содержит конфиденциальную информацию.",
        "full_name": "ФИО",
        "birth_date": "Дата рождения",
        "gender": "Пол",
        "blood_type": "Группа крови",
        "allergies": "Аллергии",
        "records_title": "Медицинские записи ({count})",
        "no_records": "Медицинских записей пока нет.",
        "type": "Тип",
        "doctor": "Врач",
        "diagnosis": "Диагноз",
        "treatment": "Лечение",
        "notes": "Примечание",
        "not_set": "—",
        "gender_M": "Мужской", "gender_F": "Женский", "gender_O": "Другое",
        "record_types": {
            "visit": "Визит", "diagnosis": "Диагноз", "prescription": "Рецепт",
            "lab_result": "Результат анализа", "procedure": "Процедура",
        },
    },
    "en": {
        "title": "Patient Medical History",
        "meta": "Document generated by the MedKarta system. This document contains confidential information.",
        "full_name": "Full name",
        "birth_date": "Date of birth",
        "gender": "Gender",
        "blood_type": "Blood type",
        "allergies": "Allergies",
        "records_title": "Medical Records ({count})",
        "no_records": "No medical records available yet.",
        "type": "Type",
        "doctor": "Doctor",
        "diagnosis": "Diagnosis",
        "treatment": "Treatment",
        "notes": "Notes",
        "not_set": "—",
        "gender_M": "Male", "gender_F": "Female", "gender_O": "Other",
        "record_types": {
            "visit": "Visit", "diagnosis": "Diagnosis", "prescription": "Prescription",
            "lab_result": "Lab result", "procedure": "Procedure",
        },
    },
}


def _get_avatar_flowable(user, size=28 * mm):
    if not user.avatar or not hasattr(user.avatar, "path"):
        return None
    try:
        if not os.path.exists(user.avatar.path):
            return None
        img = Image(user.avatar.path, width=size, height=size)
        img.hAlign = "LEFT"
        return img
    except Exception:
        return None


def build_patient_history_pdf(patient, records, lang="uz"):
    """
    Bemor va uning tibbiy yozuvlari asosida PDF baytlar oqimini (BytesIO)
    qaytaradi. `lang` — "uz", "ru" yoki "en"; noma'lum til uchun "uz"ga tushadi.
    """
    tr = TRANSLATIONS.get(lang, TRANSLATIONS["uz"])

    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        topMargin=20 * mm, bottomMargin=20 * mm,
        leftMargin=20 * mm, rightMargin=20 * mm,
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("TitleUz", parent=styles["Title"], fontSize=16, spaceAfter=4)
    meta_style = ParagraphStyle(
        "MetaUz", parent=styles["Normal"], fontSize=9,
        textColor=colors.HexColor("#55716A"), spaceAfter=16,
    )
    section_style = ParagraphStyle(
        "SectionUz", parent=styles["Heading2"], fontSize=12,
        textColor=colors.HexColor("#0E5C56"), spaceBefore=14, spaceAfter=6,
    )
    label_style = ParagraphStyle("LabelUz", parent=styles["Normal"], fontSize=9, textColor=colors.HexColor("#55716A"))
    body_style = ParagraphStyle("BodyUz", parent=styles["Normal"], fontSize=10, leading=14)

    elements = []

    full_name = f"{patient.user.first_name} {patient.user.last_name}".strip() or patient.user.username

    header_title = Paragraph(tr["title"], title_style)
    header_meta = Paragraph(tr["meta"], meta_style)
    avatar = _get_avatar_flowable(patient.user)

    if avatar:
        header_table = Table([[[header_title, header_meta], avatar]], colWidths=[125 * mm, 30 * mm])
        header_table.setStyle(TableStyle([
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("ALIGN", (1, 0), (1, 0), "RIGHT"),
        ]))
        elements.append(header_table)
    else:
        elements.append(header_title)
        elements.append(header_meta)

    elements.append(Spacer(1, 6 * mm))

    gender_display = tr.get(f"gender_{patient.gender}", tr["not_set"]) if patient.gender else tr["not_set"]

    profile_data = [
        [tr["full_name"], full_name],
        [tr["birth_date"], str(patient.date_of_birth) if patient.date_of_birth else tr["not_set"]],
        [tr["gender"], gender_display],
        [tr["blood_type"], patient.blood_type or tr["not_set"]],
        [tr["allergies"], patient.allergies or tr["not_set"]],
    ]
    profile_table = Table(profile_data, colWidths=[45 * mm, 110 * mm])
    profile_table.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#55716A")),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("LINEBELOW", (0, 0), (-1, -1), 0.5, colors.HexColor("#DCE6E2")),
    ]))
    elements.append(profile_table)
    elements.append(Spacer(1, 10 * mm))

    elements.append(Paragraph(tr["records_title"].format(count=len(records)), section_style))

    if not records:
        elements.append(Paragraph(tr["no_records"], body_style))
    else:
        for r in records:
            record_title = f"{r.visit_date.strftime('%Y-%m-%d')} — {r.title}"
            elements.append(Paragraph(record_title, section_style))
            type_label = tr["record_types"].get(r.record_type, r.record_type)
            doctor_name = r.created_by.get_full_name() or r.created_by.username
            elements.append(Paragraph(f"{tr['type']}: {type_label} · {tr['doctor']}: {doctor_name}", label_style))
            if r.diagnosis:
                elements.append(Paragraph(f"<b>{tr['diagnosis']}:</b> {r.diagnosis}", body_style))
            if r.treatment:
                elements.append(Paragraph(f"<b>{tr['treatment']}:</b> {r.treatment}", body_style))
            if r.notes:
                elements.append(Paragraph(f"<b>{tr['notes']}:</b> {r.notes}", body_style))
            elements.append(Spacer(1, 4 * mm))

    doc.build(elements)
    buffer.seek(0)
    return buffer