# Generated by Django 6.0.7 on 2026-07-21 07:29

import records.encryption
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', "Ko'rish"), ('create', 'Yaratish'), ('update', 'Tahrirlash'), ('delete', "O'chirish"), ('login', 'Kirish'), ('login_failed', 'Muvaffaqiyatsiz kirish')], max_length=20)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('visit', 'Tashrif'), ('diagnosis', 'Tashxis'), ('prescription', 'Retsept'), ('lab_result', 'Laboratoriya natijasi'), ('procedure', 'Muolaja')], default='visit', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('diagnosis', records.encryption.EncryptedTextField(blank=True)),
                ('treatment', records.encryption.EncryptedTextField(blank=True)),
                ('notes', records.encryption.EncryptedTextField(blank=True)),
                ('visit_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Erkak'), ('F', 'Ayol'), ('O', 'Boshqa')], max_length=1)),
                ('national_id', records.encryption.EncryptedCharField(blank=True, help_text='Shaxsni tasdiqlovchi hujjat raqami', max_length=500)),
                ('address', records.encryption.EncryptedTextField(blank=True)),
                ('emergency_contact', records.encryption.EncryptedCharField(blank=True, max_length=500)),
                ('blood_type', models.CharField(blank=True, max_length=5)),
                ('allergies', records.encryption.EncryptedTextField(blank=True, help_text="Ma'lum allergiyalar")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
