# Generated by Django 6.0.7 on 2026-08-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('view', "Ko'rish"), ('create', 'Yaratish'), ('update', 'Tahrirlash'), ('delete', "O'chirish"), ('login', 'Kirish'), ('login_failed', 'Muvaffaqiyatsiz kirish'), ('export', 'Eksport qilish')], max_length=20),
        ),
    ]
