# Generated by Django 6.0.7 on 2026-08-13 12:33

import django.db.models.deletion
import records.encryption
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_recordattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(help_text='Masalan: 500mg', max_length=100)),
                ('frequency', models.CharField(choices=[('once', 'Bir marta'), ('daily_1', 'Kuniga 1 marta'), ('daily_2', 'Kuniga 2 marta'), ('daily_3', 'Kuniga 3 marta'), ('daily_4', 'Kuniga 4 marta'), ('weekly', 'Haftada bir marta'), ('as_needed', "Zarurat bo'yicha")], default='daily_1', max_length=20)),
                ('duration_days', models.PositiveIntegerField(help_text='Necha kun davomida qabul qilinadi')),
                ('instructions', records.encryption.EncryptedTextField(blank=True, help_text="Qo'shimcha ko'rsatmalar")),
                ('start_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medical_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='records.medicalrecord')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='records.patient')),
                ('prescribed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date', '-created_at'],
            },
        ),
    ]
